"""Generate the AdminController, forms and models lesson from the inspected project."""
from pathlib import Path
from html import escape, unescape
import re
ROOT=Path(__file__).resolve().parents[1]
parts=[]
def p(s): return '<p>'+s+'</p>'
def code(s): return '<pre><code>'+escape(s.strip())+'</code></pre>'
def note(s): return '<aside>'+s+'</aside>'
def steps(xs): return '<ol>'+''.join('<li>'+x+'</li>' for x in xs)+'</ol>'
def table(h,rows): return '<table><thead><tr>'+''.join('<th>'+x+'</th>' for x in h)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+escape(unescape(x))+'</td>' for x in r)+'</tr>' for r in rows)+'</tbody></table>'
def section(title,goal,body):
 n=len(parts)+1;parts.append((title,f'<section class="chapter" id="lesson-{n}"><div class="eyebrow">DERS 02 · BÖLÜM {n:02}</div><h1>{title}</h1><p class="goal">{goal}</p>{body}</section>'))
section('Okumadan yazmaya geçiyoruz','SiteController içeriği gösterir; AdminController onu yönetir.',
p('Önceki derste bir URL’nin veritabanı sorgusuna ve view’a nasıl bağlandığını gördük. Bu derste ters yönü de izleyeceğiz: kullanıcı inputa bir değer yazar, form gönderilir, C# nesnesi oluşur, doğrulanır ve veritabanına kaydedilir.')+code('GET /admin/posts/ilk-yazim/edit\n  → AdminController.Editor → ContentPage → Edit.cshtml\n  → Kullanıcı formu değiştirir\nPOST /admin/posts/ilk-yazim/edit\n  → SavePost → Save → doğrulama → SaveChangesAsync\n  → Redirect → Edit.cshtml yeniden açılır\nGET /blog/ilk-yazim\n  → SiteController → güncel kayıt → ziyaretçi view’ı')+
p('Rehber, projenin 4c8cf8c sürümündeki davranışını anlatır. Uygulama kodu bu ders için değiştirilmez. Kısaltılmış kodlar öğretici örneklerdir; sonda controller’ın gerçek kodu satır numaralarıyla yer alır.')+
table(['Bileşen','Görevi'],[['AdminController','Ekranı açar, formu alır, doğrular ve kaydeder.'],['ContentPage','İçerik entity’si; bu projede aynı zamanda edit formunun modeli.'],['LoginModel','Yalnızca giriş formunun veri modeli.'],['Edit.cshtml','Entity alanlarından input üretir.'],['editor.js','Görsel metin alanlarını BodyHtml değerine aktarır.'],['SitePageViewModel','Ziyaretçi ekranı için entity ve listeleri paketler.']])+
note('Her bölümde üç soruyu sorun: Bu veri nereden geliyor? Şimdi bellekte mi, veritabanında mı? Sonuç hangi view’da kullanılıyor?'))
section('Sınıf, bağımlılıklar ve yetki','Constructor’da neden hem db hem configuration var?',code('[Authorize(Policy = "AdminAccess"), Route("admin")]\npublic class AdminController(\n    SiteDbContext db, IConfiguration configuration) : Controller')+
p('db veritabanına erişir. configuration JSON ve ortam değişkenleri gibi kaynaklardan ayar okur. İkisi de ASP.NET Core tarafından constructor’a verilir; controller bağlantı veya ayar dosyasını kendi açmaz. Bu bağımlılıkların kayıt/yükleme düzeni Program.cs’de kurulmuştur.')+
p('Route("admin") ortak adres önekidir. Bir action’daki HttpGet("posts/new") ile birleşince GET /admin/posts/new olur. Authorize, AdminAccess politikasını ister. Politikanın ayrıntısı Program.cs’de tanımlıdır: giriş kontrolü kapalıysa izin ver, açıksa kimliği doğrulanmış kullanıcı iste.')+
table(['Ayar / nitelik','Sonuç'],[['Admin:RequireAuthentication=false','Şu anki durum: /admin giriş istemez; düzenleme de anonim yapılabilir.'],['Admin:RequireAuthentication=true','Oturumsuz kullanıcı admin ekranı için login’e yönlendirilir.'],['AllowAnonymous','Login action’larına oturum açmadan erişilebilmesini sağlar.'],['EnableRateLimiting("login")','Login POST için tanımlı IP bazlı hız sınırını uygular.']])+
p('Authentication “kimlik var mı?”, authorization “bu endpoint için izin var mı?” sorusudur. AllowAnonymous bu sayfadaki form doğrulamasını veya CSRF korumasını kapatmaz. Giriş açık/kapalı tercihi ile formun güvenli gönderilmesi ayrı konulardır.')+
note('Şu an login ekranı görünmüyor diye giriş kodu silinmiş değil. Ayar false olduğu için Login action’ı /admin’e yönlendiriyor.'))
section('Route → action → view haritası','Aynı URL’nin GET ve POST istekleri farklı iş yapar.',table(['HTTP ve adres','Action / yardımcı','Sonuç'],[
['GET /admin','Index','Index.cshtml + List<ContentPage>'],['GET /admin/pages/{slug}/edit','EditPage → Editor','Edit.cshtml + sabit ContentPage'],['GET /admin/posts/{slug}/edit','EditPost → Editor','Edit.cshtml + detay ContentPage'],['GET /admin/posts/new','New','Edit.cshtml + yeni ContentPage'],['POST /admin/pages/{slug}/edit','SavePage → Save','Kayıt veya hatalı Edit formu'],['POST /admin/posts/{slug}/edit','SavePost → Save','Kayıt veya hatalı Edit formu'],['POST /admin/posts/new','Create → Save','INSERT veya hatalı Edit formu'],['GET /admin/login','Login()','Login.cshtml veya redirect'],['POST /admin/login','Login(LoginModel)','Doğrulama ve oturum'],['POST /admin/logout','Logout','Oturumu kapatma ve redirect']])+
p('GET ekranı okumak ve göstermek içindir. POST kullanıcıdan veri alan işleme gider. Aynı URL’ye sahip iki metot, HttpGet/HttpPost nitelikleri sayesinde ayrılır. İki Login metodunun parametrelerinin farklı olması da C# metot aşırı yükleme örneğidir.')+
p('Editor ve Save private yardımcı metotlardır; dışarıya ayrı route olarak açılmazlar. EditPage/EditPost aynı düzenleme işini farklı IsDetail değeriyle kullanır. SavePage/SavePost/Create da ortak doğrulama-kayıt işini paylaşır. Amaç aynı kodu üç kez yazıp zamanla farklı davranmasına yol açmamaktır.')+
note('View("Edit", page) yeni bir GET isteği başlatmaz; mevcut isteğin yanıtında Edit view’ını çizer. Redirect(...) ise tarayıcıya başka adrese yeni istek yapmasını söyler.'))
section('Index: listeyi ekrana taşıma','Veritabanı sıralaması ile view içindeki gruplama arasındaki fark.',code('public async Task<IActionResult> Index() =>\n    View(await db.Pages.AsNoTracking()\n        .OrderBy(p => p.IsDetail)\n        .ThenBy(p => p.Title)\n        .ToListAsync());')+
p('AsNoTracking okuma içindir. OrderBy önce sabit sayfaları, ardından detayları sıralar; ThenBy aynı grup içinde başlığa göre sıralar. ToListAsync sonuçları getirir. View adı verilmediği için action adı Index kullanılır; dosya Views/Admin/Index.cshtml olur.')+code('@model List<ContentPage>\n@foreach (var detail in new[] { false, true })\n{\n    foreach (var entry in Model.Where(p => p.IsDetail == detail))\n    {\n        <a href="@entry.Url">@entry.Title</a>\n    }\n}')+
p('Bu Razor örneği sadeleştirilmiştir. Önemli fark: Controller’daki LINQ EF sorgusudur; view’daki Model artık bellekte List<ContentPage> olduğundan Where bellekte gruplar. View’daki her Where yeni SQL göndermez.')+
p('Admin listesi Published filtresi kullanmaz. Taslaklar da görünmelidir; aksi halde onları yeniden yayınlamak veya düzeltmek mümkün olmazdı. Ziyaretçi listesi ise yalnızca yayınlanmış kayıtları gösterir.')+
p('Düzenleme bağlantısı IsDetail değerinden üretilir: sabit sayfada /admin/pages/about/edit, yazıda /admin/posts/ilk-yazim/edit. Url ise ziyaretçi bağlantısıdır. Yönetim linki ile ziyaretçi linkinin aynı olmaması gerekir.')+
note('View model alanı ile HTML etiketi aynı şey değildir: Title veridir; onu h1, td veya a içinde göstermek view’ın kararıdır. Görünümü değiştirmek her zaman veritabanı değişikliği gerektirmez.'))
section('Editor: mevcut formu açma','GET sırasında BodyHtml değişiyor; bu hemen veritabanına yazılır mı?',code('var page = await db.Pages.AsNoTracking()\n    .SingleOrDefaultAsync(p => p.Slug == slug && p.IsDetail == detail);\nif (page == null) return NotFound();\npage.BodyHtml = page.IsDetail ? BlogMarkup.ArticleBody(page.BodyHtml)\n    : page.Slug is "home" or "blog"\n        ? BlogMarkup.ListingTemplate(page.BodyHtml) : page.BodyHtml;\nreturn View("Edit", page);')+
steps(['URL’deki slug ve route’un belirlediği detail ile kayıt aranır.', 'Kayıt yoksa NotFound ile işlem sonlanır.', 'Blog detayında eski şablondan yalnızca makale gövdesi çıkarılır.', 'Ana sayfa/blogda örnek kart alanı BLOG_LIST işaretine uyarlanır.', 'Hazırlanan ContentPage, Edit.cshtml’e gönderilir.'])+
p('Burada page.BodyHtml ataması yalnızca bellekteki nesneyi değiştirir. Sorgu AsNoTracking ile çalışmıştır ve SaveChangesAsync de çağrılmamıştır. Formu açıp kapatmak veritabanını güncellemez. Ancak bu hazırlanmış değer formda görünür; kullanıcı kaydederse POST yolundan kalıcı olur.')+
p('Neden Published kontrolü yok? Taslak yazının editörü de açılmalıdır. Neden ArticleBody uygulanıyor? Yönetici makale yazarken header/footer ve eski örnek yorumlarla uğraşmasın; dinamik başlıklar ayrı alanlardan yönetilsin.')+
note('Bir nesnenin özelliğine değer atamak her zaman SQL UPDATE değildir. Kalıcılık için doğru context takibi ve kaydetme adımı gerekir. Bu ayrım GET ile POST arasındaki en önemli farklardan biridir.'))
section('New: kayıt oluşturmadan form hazırlamak','Yeni nesne ile yeni veritabanı satırı aynı şey değildir.',code('public IActionResult New() => View("Edit", new ContentPage {\n    IsDetail = true, Published = false, Category = "Genel",\n    CoverImageUrl = "/images/blog-post-bg.jpg",\n    BodyHtml = "<section><p>Yazınızı buraya ekleyin.</p></section>"\n});')+
p('HTML örneği kısaltılmıştır. new ContentPage bellekte bir nesne oluşturur. Add ve SaveChanges olmadığı için tabloya satır eklenmez. Id varsayılan int değeri 0 olduğu için Edit view’ı “Yeni detay” başlığını seçer; mevcut kayıtta ise Title gösterir.')+
table(['Başlangıç alanı','Neden böyle?'],[['IsDetail=true','Bu ekran blog yazısı oluşturuyor.'],['Published=false','Tamamlanmamış yazı kaydedilirse hemen ziyaretçiye açılmasın.'],['Category="Genel"','İlk form için düzenlenebilir başlangıç değeri.'],['CoverImageUrl','Başlangıç görsel yolu; dosya yüklemez.'],['BodyHtml','Görsel editörün düzenleyebileceği başlangıç paragrafı.']])+
p('Neden ayrı New.cshtml yok? Yeni yazı ve mevcut yazı aynı alanları düzenliyor. Tek Edit view’ı ile alan görünümü ve hata gösterimi ortak tutuluyor. Formun gönderildiği URL farklı olduğu için POST yeni kayıtta Create action’ına, mevcut kayıtta SavePost action’ına gidiyor.')+
p('ContentPage sınıfında Published varsayılanı true olmasına rağmen New burada açıkça false veriyor. Nesne oluşturulurken yapılan bu atama başlangıç değerini değiştirir. Böylece aynı model farklı kullanımda farklı başlangıç davranışı gösterebilir.')+
note('Tarayıcıda formu açmak, sayfayı yenilemek veya vazgeçmek bir yazı oluşturmamalıdır. Yeni kayıt ancak başarılı POST akışındaki Add + SaveChangesAsync ile oluşur.'))
section('Edit.cshtml: input nereden değer alıyor?','asp-for, name ve model binding ilişkisi.',code('@model ContentPage\n<form method="post">\n    @Html.AntiForgeryToken()\n    <div asp-validation-summary="All"></div>\n    <label asp-for="Title">Başlık</label>\n    <input asp-for="Title" maxlength="160" required>\n    <textarea asp-for="Description"></textarea>\n    <input asp-for="Published">\n    <textarea asp-for="BodyHtml"></textarea>\n    <button>Değişiklikleri kaydet</button>\n</form>')+
p('Bu, mevcut formun sadeleştirilmiş halidir. @model ContentPage view’ın beklediği türü belirtir. Model, controller’dan gelen nesnedir. asp-for="Title" modeldeki Title özelliğine bağlanır; name="Title", id ve mevcut değer gibi HTML özelliklerini üretir. Model binding POST’taki Title değerini input.Title özelliğine taşır.')+
p('Formda action yok; tarayıcı POST’u mevcut URL’ye gönderir. Label’daki asp-for etiketi ilgili inputla ilişkilendirir. HTML placeholder örnek ipucudur, veritabanına kaydedilecek gerçek değer değildir.')+
table(['View’daki ifade','Gönderim / anlam'],[['input asp-for="Title"','Title adlı form alanı → input.Title'],['textarea asp-for="BodyHtml"','HTML metni → input.BodyHtml'],['input asp-for="Published"','Bool checkbox; false gönderimi için yardımcı hidden alan da üretilebilir.'],['Html.AntiForgeryToken()','CSRF kontrolüne ait gizli token; entity alanı değil.'],['asp-validation-summary="All"','ModelState içindeki hataları kullanıcıya gösterir.']])+
note('Sadece name="BaskaAd" yaparsanız Title ile otomatik eşleşme bozulur. Etiket metnini “Yazı başlığı” yapmak ise binding’i değiştirmez. Kullanıcının gördüğü label ile sunucunun bağladığı alan adı ayrı şeylerdir.'))
section('Koşullu alanlar ve layout','Neden bazı inputlar yalnızca blogda görünüyor?',
p('Edit view’ında Model.IsDetail kontrolü kapak, kategori, yazar ve yazı tarihini yalnızca blog detayında gösterir. Sabit sayfada Slug readonly olur. Ana sayfa ve blog sabit sayfasında ise kartların otomatik oluştuğunu anlatan bilgi gösterilir.')+
code('@if (Model.IsDetail)\n{\n    <input asp-for="Author">\n    <input asp-for="PublishedAtUtc" type="datetime-local"\n           asp-format="{0:yyyy-MM-ddTHH:mm}">\n}')+
p('Tarih formatı inputun beklediği biçimi sağlar. datetime-local saat dilimi taşımaz; projede alan açıkça UTC diye etiketlenmiştir. Controller’da SpecifyKind(...Utc) sayısal saati dönüştürmez, UTC olarak işaretler. Yerel saati otomatik UTC’ye çevirdiğini düşünmeyin.')+
steps(['Views/_ViewImports.cshtml modellerin namespace’ini ve MVC Tag Helper’larını etkinleştirir.', 'Kök _ViewStart normal _Layout seçer; Admin/_ViewStart bunu _AdminLayout ile değiştirir.', '_AdminLayout header, admin.css, çıkış formu ve bildirim alanını içerir.', 'RenderBody(), Index/Edit/Login view’ının HTML’sini ortak kabuğa yerleştirir.'])+
p('Admin view’ları kendi başlarına tam html/head/body belgeleri değildir. Ortak kabuk layouttan gelir. Ziyaretçi Page.cshtml ise Layout=null kullanır ve tam belgeyi kendisi kurar. Aynı yaklaşımı her ekrana zorla uygulamak yerine mevcut yapının amacını görmek önemlidir.')+
note('Readonly görünüm için yararlıdır ama sunucu güvenliği değildir. Kullanıcı farklı POST gönderebilir. Save metodunda sabit slug’ın değişmediği ayrıca kontrol edilir.'))
section('POST: route değeri mi, form değeri mi?','Slug değiştirirken iki farklı slug aynı anda vardır.',code('public Task<IActionResult> SavePost(\n    [FromRoute] string slug, ContentPage input)\n    => Save(slug, true, input);\n\npublic Task<IActionResult> Create(ContentPage input)\n    => Save(null, true, input);')+
p('Örnek: URL /admin/posts/eski-ad/edit, formdaki Slug ise yeni-ad. slug parametresi mevcut kaydı bulmak için eski-ad olmalıdır. input.Slug yeni kaydedilecek değerdir. FromRoute özellikle URL’deki değerin kullanılacağını belirtir; formdaki aynı isimli alanla karışmasını engeller.')+
table(['Değer','Kaynağı','Amacı'],[['oldSlug','URL; yenide null','Mevcut kaydı bulmak / yeni kayıt ayrımı'],['input.Slug','POST formu','Kaydedilecek yeni adres'],['detail','SavePost/SavePage action’ı','Yazı mı sabit sayfa mı?'],['input','Model binding','Gönderilen alanları taşıyan geçici nesne']])+
p('SavePage false, SavePost true, Create null/true gönderir. Kullanıcının formda IsDetail=true göndermesi sabit sayfa endpointini blog endpointine dönüştürmez; Save bu değeri route’a göre yeniden atar.')+
p('Task doğrudan döndürüldüğünden bu kısa action’larda async/await yoktur. Asenkron işlemler ortak Save içinde beklenir. Metotların küçük olması işin önemsiz olduğunu değil, işi tek ortak yere aktardığını gösterir.')+
note('Bu action’lar yalnızca POST kabul eder. Aynı URL’ye GET ile gitmek düzenleme formunu açan action’ı seçer; kayıt işlemini çalıştırmaz.'))
section('Save: input ve page neden iki nesne?','İstemci verisini gerçek entity’ye kontrollü aktarmak.',code('input.IsDetail = detail;\nvar page = oldSlug == null\n    ? new ContentPage { IsDetail = true }\n    : await db.Pages.SingleOrDefaultAsync(p =>\n        p.Slug == oldSlug && p.IsDetail == detail);\nif (page == null) return NotFound();\ninput.Id = page.Id;')+
p('input, formdan gelen nesnedir. page, veritabanından yüklenen takipli kayıt veya yeni oluşturulan gerçek entity’dir. Burada AsNoTracking kullanılmaz; mevcut page üzerindeki değişikliklerin SaveChangesAsync tarafından bulunması istenir.')+
p('oldSlug null ise yeni kayıt oluşturulur. Null değilse doğru tür ve eski slug ile kayıt aranır. Başkası kaydı kaldırmışsa veya URL yanlışsa NotFound döner. input.Id gerçek page.Id ile değiştirilir; gelen Id değerine güvenilmez. Bu Id özellikle hata halinde edit view’ının mevcut/yeni kayıt ayrımı için de önemlidir.')+
code('page.Title = input.Title;\npage.Slug = input.Slug;\npage.Description = input.Description ?? "";')+
p('Neden doğrudan db.Update(input) kullanılmıyor? İstemci tarafından gönderilebilecek tüm entity özelliklerinin otomatik kayda aktarılması yerine hangi alanların değişeceği açıkça seçiliyor. IsDetail, Id ve UpdatedUtc sunucunun kontrolünde tutuluyor. Bu yaklaşım ayrı input modeli bulunmasa bile kontrolü artırıyor.')+
note('Bu işlem yeni HTTP isteğinde gerçekleşir. GET’te oluşturulan page nesnesi POST boyunca bellekte bekletilmiyor. POST kendi inputunu oluşturuyor ve gerçek kaydı yeniden veritabanından yüklüyor.'))
section('Doğrulama: neden üç katman var?','HTML, ModelState ve veritabanı birbirinin yerine geçmez.',code('if (!detail && oldSlug != input.Slug)\n    ModelState.AddModelError("Slug", "Sabit sayfaların route’u değiştirilemez.");\nif (await db.Pages.AnyAsync(p => p.IsDetail == detail\n    && p.Slug == input.Slug && p.Id != page.Id))\n    ModelState.AddModelError("Slug", "Bu slug zaten kullanılıyor.");\nif (!ModelState.IsValid) return View("Edit", input);')+
p('AnyAsync yalnızca böyle bir kayıt var mı diye sorar; liste getirmez. p.Id != page.Id koşulu, mevcut yazının kendi slug’ıyla çakışmış sayılmamasını sağlar. Başka kayıtta aynı tür/slug varsa hata eklenir.')+
table(['Katman','Örnek','Neden var?'],[['Tarayıcı','required, maxlength, readonly','Hızlı kullanıcı geri bildirimi; tek güvence değil.'],['Model / controller','Required, regex, ModelState','Tarayıcı dışından gelen isteği de denetler.'],['Veritabanı','UNIQUE(IsDetail,Slug)','Eşzamanlı iki isteğin aynı slug’ı oluşturmasına son engel.']])+
p('ModelState model binding sırasında oluşan dönüştürme hatalarını ve doğrulama hatalarını tutar. Örneğin tarih alanı tarihe çevrilemiyorsa veya slug büyük harf içeriyorsa geçersiz olabilir. Hata halinde View("Edit", input) kullanıcının girdilerini koruyarak aynı formu gösterir; redirect yapılmaz.')+
p('AddModelError("Slug", ...) belirli alana; AddModelError("", ...) genel forma hata ekler. asp-validation-summary="All" ikisini de gösterebilir. ModelState’in sakladığı gönderilmiş değerler, hata formunda Tag Helper’ların yeniden çizdiği değerlere öncelik verebilir; model özelliğini değiştirmek her zaman ekrandaki hatalı girdiyi değiştirmez.')+
note('HTTP 200, kaydın başarılı olduğunu tek başına göstermez. Geçersiz form da hata mesajlarıyla 200 dönebilir. Başarılı Save akışı burada redirect üretir.'))
section('Alan atamaları ve boş değerler','Null, boş string ve tarih kararlarının amacı.',code('page.CoverImageUrl = string.IsNullOrWhiteSpace(input.CoverImageUrl)\n    ? null : input.CoverImageUrl.Trim();\npage.Category = string.IsNullOrWhiteSpace(input.Category)\n    ? null : input.Category.Trim();\npage.Author = string.IsNullOrWhiteSpace(input.Author)\n    ? null : input.Author.Trim();\npage.PublishedAtUtc = DateTime.SpecifyKind(input.PublishedAtUtc, DateTimeKind.Utc);')+
p('Bu alanlar yalnızca detail=true için atanır. IsNullOrWhiteSpace null, boş metin veya sadece boşluk girilmiş olmasını tek yerde kontrol eder. Dolu değerler Trim ile baş/son boşluklarından temizlenir. Böylece " Gezi " gibi istemeden farklı görünen değerler azaltılır.')+
p('Description farklı davranır: input.Description ?? "". DbContext bu sütunu zorunlu tanımladığı için null yerine boş string saklanır. Modelin C# tarafında nullable olması ile veritabanının null kabul etmesi ayrı ayarlardır.')+
p('BodyHtml için blogda ArticleBody, ana sayfa/blog listesinde ListingTemplate uygulanır. Bu, bilinen Voku şablon yapısını düzenler; genel bir HTML sanitizer değildir. Published formdan alınır, UpdatedUtc ise DateTime.UtcNow ile sunucuda yenilenir.')+
table(['Tarih','Amacı'],[['PublishedAtUtc','Yönetilebilir gösterim ve sıralama tarihi. İleri tarih otomatik zamanlama oluşturmaz.'],['UpdatedUtc','Son kaydın sunucu zamanı. Kullanıcı formundan alınmaz.']])+
note('Görsel alanının regex’i adres biçimini sınırlar; dosyanın gerçekten var olduğunu veya yüklenebildiğini kanıtlamaz. Kapak yolu yazmak bir dosya upload işlemi değildir.'))
section('INSERT, UPDATE ve slug bağlantıları','Add ile SaveChangesAsync neden ayrı?',code('if (oldSlug == null) db.Pages.Add(page);\nelse if (detail && oldSlug != page.Slug)\n{\n    foreach (var linked in await db.Pages\n        .Where(p => p.BodyHtml.Contains(oldUrl)).ToListAsync())\n        linked.BodyHtml = linked.BodyHtml\n            .Replace("\\\"" + oldUrl + "\\\"", "\\\"" + page.Url + "\\\"")\n            .Replace("\'" + oldUrl + "\'", "\'" + page.Url + "\'");\n}\nawait db.SaveChangesAsync();')+
p('Add, yeni entity’nin INSERT ile kaydedileceğini context’e bildirir. Mevcut entity zaten takipli sorguyla alındığından özellik atamaları değişiklik olarak izlenir; ayrıca Add yapılmaz. SaveChangesAsync bekleyen değişiklikleri veritabanına gönderir. Önceki atamalar yalnızca bellekteydi.')+
p('Slug değişiyorsa önceki URL oldUrl içinde korunmuştur. Eski adresi içeren BodyHtml kayıtları aranır; tek/çift tırnak içinde tam eşleşen bağlantılar yeni adresle değiştirilir. Aynı kaydetme çağrısında bu takipli kayıtlar da güncellenir.')+
p('Dinamik kartların bağlantısı post.Url’den hesaplandığı için HTML Replace işlemine ihtiyaç duymaz. Bu döngü elle yazılmış mevcut HTML bağlantıları içindir. Harici sitelerdeki linkleri, farklı query/fragment biçimlerini veya her tür HTML yazımını dönüştüren tam bir parser değildir.')+
note('Eski slug için redirect geçmişi tutulmaz. /blog/eski-ad artık 404 olabilir. Slug değişikliğiyle mevcut iç bağlantıyı değiştirmek, dışarıdan gelen eski URL’yi kalıcı yönlendirmekle aynı özellik değildir.'))
section('Hata, başarı ve yönlendirme','Neden başarılı POST sonrası tekrar GET yapılıyor?',code('try { await db.SaveChangesAsync(); }\ncatch (DbUpdateException)\n{\n    ModelState.AddModelError("", "Kayıt tamamlanamadı. Slug başka bir kayıtta kullanılıyor olabilir.");\n    return View("Edit", input);\n}\nTempData["Success"] = "İçerik kaydedildi.";\nreturn Redirect(detail\n    ? $"/admin/posts/{page.Slug}/edit"\n    : $"/admin/pages/{page.Slug}/edit");')+
p('Ön kontrol geçse bile başka istek aynı anda aynı slug’ı kaydedebilir. Veritabanı benzersiz indeksi bunu engeller; SaveChangesAsync hata verebilir. Catch, DbUpdateException yakalayıp formu mesajla döndürür. Ancak bu exception yalnızca slug hatası değildir; mesaj olası nedeni belirtir, kesin teşhis yerine geçmez.')+
p('Başarılı akış POST → 302 redirect → GET biçimindedir. Bu düzen, kullanıcı başarı ekranını yenilediğinde aynı formu tekrar gönderme riskini azaltır. Redirect aynı kaydın yeni slug adresine yapıldığı için editörde güncel route görünür.')+
p('TempData mesajı yönlendirmeden sonraki isteğe taşır. _AdminLayout, TempData["Success"] string ise role="status" olan bildirim paragrafında gösterir. Sıradan yerel değişken redirect sonrası yeni isteğe aktarılmaz.')+
note('Return View ile Redirect farkını pratikte görün: geçersiz slug gönderince aynı form hata gösterir; geçerli kayıtta Network sekmesinde önce POST, ardından GET görünür.'))
section('LoginModel, hash ve cookie','Giriş kontrolü tekrar açılırsa bu kod nasıl çalışacak?',
steps(['GET Login(), ayar true ise new LoginModel ile Login.cshtml açar; false ise Index’e yönlendirir.', 'POST Login(input), önce ayarı ve ModelState’i kontrol eder.', 'AdminUsers içinde Username eşleşen kullanıcıyı arar.', 'Kayıt yoksa veya PasswordHasher doğrulaması başarısızsa genel hata mesajı verir.', 'Başarıda kullanıcı adı claim’i olan kimlik oluşturur; SignInAsync authentication cookie’sini üretir.', 'Index’e yönlendirir. Sonraki isteklerde middleware cookie’den kullanıcı kimliğini okur.', 'POST Logout(), SignOutAsync ile tarayıcı oturumunu kapatır; login’e yönlendirir.'])+
p('LoginModel.Password düz şifre girişidir; AdminUser.PasswordHash saklanan doğrulama değeridir. Şifreyi bulmak için hash’i geri çözme akışı yoktur. DataType.Password inputun görünümünü belirtir; kendisi hashleme yapmaz. Hash kontrolünü PasswordHasher yapar.')+
p('ClaimsPrincipal kullanıcının kimlik bilgisini taşır. ClaimTypes.Name bu kodda kullanıcı adıdır. Tam ASP.NET Core Identity kullanıcı/rol sistemi kurulmuş değildir; yalnızca PasswordHasher ve cookie authentication bileşenleri kullanılır. Rol tabanlı yetki ayrımı yoktur.')+
p('Cookie adının Voku.Admin olması ve dört saatlik bilet süresi Program.cs’de ayarlanır. Login POST için IP bazlı dakikada 10 istek limiti tanımlanır. Çıkışın POST olması, durum değiştiren bir işlem olmasıyla uyumludur; layout formu antiforgery token gönderir.')+
note('Şu an ayar false olduğu için hesap şifresi bu ekranların ön koşulu değil. Buna rağmen login akışını öğrenmek, ayar yeniden true yapıldığında hangi kodun devreye gireceğini anlamanızı sağlar.'))
section('Entity, input model ve view model','Neden her model için bir tablo yok?',table(['Tür','Nerede kullanılıyor?','Tablo / amaç'],[['ContentPage','EF, Admin/Edit, Save parametresi','Pages entity’si; mevcut projede üç görev bir sınıfta.'],['AdminUser','Girişte kullanıcı sorgusu','AdminUsers entity’si; hash saklar.'],['LoginModel','Login.cshtml ve POST Login','Form girdisi; DbSet olmadığı için ayrı tablo yok.'],['SitePageViewModel','SiteController → Site/Page','Ekran paketi; entity + listeler + sayfalama.']])+
p('Entity verinin kalıcı biçimini, input modeli kullanıcının gönderebileceği alanları, view model ekranın ihtiyaç duyduğu veri paketini anlatır. İsimde Model geçmesi tek başına “veritabanı tablosu” demek değildir. EF eşlemesi DbContext/model yapılandırmasına bağlıdır.')+
p('Bu küçük projede ContentPage hem entity hem edit modeli seçilerek alanların tekrar yazılması azaltılmış. Bedeli, kalıcılık ayrıntılarının forma da görünür olmasıdır. Bu yüzden Save, Id ve IsDetail gibi alanları istemciden alıp körlemesine kaydetmez; izin verilen alanları tek tek kopyalar.')+
code('// Gelecekte değerlendirilebilecek tasarım; mevcut kod değil:\npublic class EditPostInput\n{\n    public string Title { get; set; } = "";\n    public string Slug { get; set; } = "";\n    public string BodyHtml { get; set; } = "";\n}\n// POST EditPostInput alır; gerçek entity ayrıca yüklenir.')+
p('Ayrı input modeli özellikle daha fazla yetki, çoklu form veya karmaşık veri ilişkisi olduğunda hangi alanların değiştirilebileceğini açıklaştırır. SitePageViewModel ise birkaç farklı sorgu sonucunu aynı view’a taşımak için zaten ayrılmıştır.')+
note('DbContext’te Pages ve AdminUsers vardır. Yazar adı Author bir string’dir; AdminUser’a foreign key bağlantısı yoktur. Category de ayrı tablo ilişkisi değil string alandır. Bu yüzden mevcut sistemi ilişkili kullanıcı/kategori sistemi gibi düşünmeyin.'))
section('ContentPage alanlarının tasarım amacı','Hangi alan kullanıcıdan gelir, hangisi hesaplanır?',table(['Alan','Kaynak / kural','Niçin?'],[['Id','Veritabanı anahtarı; form belirlemez','Kaydı güvenilir biçimde ayırır.'],['Title','Zorunlu, en çok 160','Liste ve detay ana başlığı.'],['Slug','Zorunlu, 120, küçük harf/rakam/tire','Okunabilir benzersiz adres.'],['IsDetail','Endpoint belirler','Sabit sayfa ile yazıyı aynı tabloda ayırır.'],['BodyHtml','Zorunlu HTML gövdesi','Zengin içerik ve Voku düzenini korur.'],['Description','300; kayıt sırasında null yerine boş string','Özet ve SEO açıklaması.'],['CoverImageUrl','500; yerel yol veya HTTPS biçimi','Kart/detay ortak görseli.'],['Category / Author','80 / 100; boşsa null','Filtre ve yazar metni.'],['PublishedAtUtc','Formun UTC tarihi','Sıralama ve görünür tarih.'],['Published','Form bool değeri','Ziyaretçiye açık mı?'],['UpdatedUtc','Sunucuda DateTime.UtcNow','Son kayıt zamanı.'],['Url','Slug ve IsDetail’den hesaplanır','Aynı adres bilgisini iki kez saklamaz.']])+
p('Required, StringLength ve RegularExpression attribute’ları model doğrulamasına katılır. HTML’de required/maxlength yazılması bu sunucu kurallarının yerine geçmez. StringLength’in SQLite’da tek başına katı uzunluk sınırı oluşturduğunu varsaymayın; bu projede MVC doğrulaması önemlidir.')+
p('DbContext Url alanını Ignore eder: sütun üretilmez. IsDetail/Slug birleşik unique indeksi aynı türde çakışmayı önler. Description için IsRequired, nullable C# özelliğine rağmen veritabanında NOT NULL istediğimizi belirtir. Bu yüzden Save boş açıklamayı dönüştürür.')+
note('Bir alanın ekranda gösterilmesi, onun veritabanında ayrı sütun olmasını gerektirmez. Url ve sayfalama TotalPages bunun iki örneğidir.'))
section('Görsel editörün görünmeyen bağlantısı','Birçok kutu var ama neden yalnızca BodyHtml kaydediliyor?',code('const doc = new DOMParser().parseFromString(source.value, "text/html");\nconst sync = () => { source.value = doc.body.innerHTML; };\ninput.addEventListener("input", () => {\n    update(input.value);\n    sync();\n});')+
p('source, id=BodyHtml olan textarea’dır. editor.js bu metni geçici DOM belgesine çevirir. Metin elemanları için input/textarea, bağlantılar için href, görseller için src/alt alanları üretir. Kullanıcı alanı değiştirdikçe geçici belge ve asıl textarea güncellenir.')+
steps(['GET Editor, BodyHtml’yi Edit view’ına gönderir.', 'asp-for textarea’sı bu değeri taşır.', 'JavaScript görsel alanları oluşturur.', 'Kullanıcı paragrafı değiştirir; sync() tüm body HTML’sini textarea’ya yazar.', 'Normal form POST’u BodyHtml alanını gönderir.', 'Save input.BodyHtml değerini gerçek entity’ye aktarır ve kaydeder.'])+
p('Görsel alanların her biri için ayrı veritabanı sütunu veya endpoint yoktur. İç içe HTML elemanları bulunan metinler görsel editörde tek kutu olarak açılmaz; yapı bozulmasın diye gelişmiş HTML alanı kullanılabilir. Görsel yolu değiştirmek dosya yüklemek değildir.')+
p('cms.js ziyaretçi form gönderimini durdurur; admin layoutu onu yüklemez. Admin/Edit yalnızca editor.js ekler ve normal POST çalışır. “İletişim formu gönderilmiyor ama admin kaydediyor” farkının kaynağı hangi scriptin hangi view’da yüklendiğidir.')+
note('Razor’daki textarea, BodyHtml metnini editörde kodlanmış biçimde gösterir. Ziyaretçi tarafında Html.Raw ile markup olarak çizilir. HTML’i düzenlemek ile HTML’i çalışır görünüm olarak sunmak ayrı aşamalardır.'))
section('View’da değişiklik yapınca neler gerekir?','Sadece görünüm değişikliği ile yeni veri alanını ayıralım.',table(['İstek','Değişiklik yeri','Migration?'],[['Buton metni veya renk değişsin','Edit.cshtml / admin.css','Hayır.'],['Başlık etiketi farklı yazsın','label metni; asp-for aynı kalabilir','Hayır.'],['Var olan Author kartta gösterilsin','_BlogListing.cshtml','Hayır; veri zaten geliyor.'],['Yeni ReadingMinutes alanı saklansın','Entity + migration + form + Save + ziyaretçi view','Evet.'],['Kartlarda Title yerine Heading adı kullanılsın','Ayrı view model / projection','Veritabanı adı değişmiyorsa hayır.']])+
p('<b>Öğretici alıştırma, mevcut özellik değil:</b> ReadingMinutes eklemek için int? alanını ContentPage’de tanımlayın; örneğin Range ile makul değerleri doğrulayın. Yeni migration üretip uygulanacak şemayı inceleyin. Edit’e asp-for input, Save’e açık atama, kart/detaya gösterim ekleyin. Son olarak POST ile kaydedilip GET’te göründüğünü test edin.')+
code('// Alıştırma örneği; uygulamaya eklenmedi:\n[Range(1, 240)]\npublic int? ReadingMinutes { get; set; }\n\n// Edit.cshtml:\n<input asp-for="ReadingMinutes">\n\n// Save içinde:\npage.ReadingMinutes = input.ReadingMinutes;')+
p('Neden bütün adımlar gerekiyor? Input olmadan kullanıcı değer giremez. Save ataması olmadan gönderilen değer kalıcı entity’ye taşınmaz. Migration olmadan eski veritabanında sütun olmaz. Ziyaretçi view’ı kullanmazsa kaydedilen veri görünmez.')+
note('Bu çalışma bir eğitim belgesidir; örnek alan eklenmedi. Amaç, tek bir input eklemenin neden her zaman özelliği tamamlamadığını göstermek.'))
section('Bir düzenlemeyi baştan sona izleyelim','Yazar adını değiştirip ziyaretçi kartında görelim.',
steps(['GET /admin/posts/ilk-yazim/edit → EditPost → Editor.', 'Editor ContentPage’yi alır; Edit view’ında input asp-for="Author" mevcut yazar adıyla dolar.', 'Kullanıcı Author alanına “Ayşe” yazar. Henüz SQLite değişmez.', 'Form POST olur; token doğrulanır, model binding input.Author="Ayşe" yapar.', 'SavePost eski slug’ı route’tan alır ve Save’e aktarır.', 'Save gerçek page entity’sini takipli yükler, doğrulamayı kontrol eder.', 'Trim edilmiş Author değeri page.Author’a atanır; UpdatedUtc güncellenir.', 'SaveChangesAsync veritabanını yazar. TempData mesajı konur, edit URL’sine yönlendirilir.', 'Yeni GET formda “Ayşe”yi gösterir.', 'Ziyaretçi /blog açınca SiteController Posts listesinde güncel entity’yi getirir; _BlogListing @post.Author ile “Ayşe”yi gösterir.'])+
p('<b>Hata varyasyonu:</b> Aynı anda geçersiz slug gönderin. ModelState başarısız olduğundan SaveChanges’e ulaşılmaz. Formda girdiğiniz yazar adı görünebilir ama veritabanındaki yazar değişmemiş olabilir. Formda bir değerin görünmesi tek başına kaydedildiğinin kanıtı değildir.')+
p('<b>Taslak varyasyonu:</b> Published kutusunu kaldırıp kaydedin. Admin listesi kaydı göstermeye devam eder; ziyaretçi listesi ve detay sorgusu Published şartıyla dışlar. Veritabanından silinmemiştir, yayın durumu değişmiştir.')+
note('Breakpoint noktaları: Save başlangıcı → ModelState kontrolü → page.Author ataması → SaveChangesAsync sonrası. input ile page değerlerini ayrı ayrı izleyin. Tarayıcı Network’te POST ve takip eden GET’i görün.'))
section('Kontrol soruları ve mevcut sınırlar','Neyi öğrendik, bu uygulamada henüz ne yok?',table(['Soru','Cevap'],[['Formun name alanı neden önemli?','Model binding hangi özelliğe atama yapacağını onunla eşleştirir.'],['GET formunu açmak niçin kayıt oluşturmaz?','New/Editor Add + SaveChanges çağırmaz.'],['AsNoTracking neden Editor’da var, Save’de yok?','Editor gösterim için okur; Save mevcut entity değişikliklerini takip ettirir.'],['input.Slug ile oldSlug neden farklı olabilir?','Form yeni adresi, route mevcut kaydın eski adresini taşır.'],['LoginModel için migration gerekir mi?','EF entity’si olarak eşlenmiyor; yalnızca form modeli.'],['Title değişince başka view’a veri nasıl gider?','Sonraki SiteController sorgusu güncel entity’yi getirir.'],['Category bir foreign key mi?','Hayır; bu sürümde string alan.'],['CSRF token giriş kontrolü mü?','Hayır; yetki politikası ayrı, form isteği doğrulaması ayrı.']])+
p('Mevcut sistemde ayrı edit input modeli, eşzamanlı düzenleme çatışması tespiti, sürüm geçmişi, silme endpointi, slug yönlendirme tablosu ve yönetici şifre sıfırlama komutu yoktur. Her eksik özellik bu dersin hatası değildir; uygulamanın mevcut kapsamıdır.')+
p('HTML gövdesi güvenilir yönetici düzenlemesi için tasarlanmıştır. BlogMarkup bir sanitizer değildir. ModelState bazı biçimleri doğrular; her iş kuralını kendiliğinden keşfetmez. Örneğin kapak adresinin erişilebilir olması ayrı bir kontroldür.')+
note('Son alıştırma: “Edit.cshtml’de bir değeri değiştirince hangi action çalışır, hangi modele bağlanır, hangi entity’ye kopyalanır, hangi satırda kalıcı olur ve ziyaretçi view’ında nasıl görünür?” sorusunu Title ve Author için ayrı cevaplayın.'))

lines=(ROOT/'Voku.Web/Controllers/AdminController.cs').read_text().splitlines()
for first in range(0,len(lines),24):
 last=min(first+24,len(lines))
 section(f'Kod referansı · {first+1}–{last}', 'Mevcut AdminController.cs; uzun satırlar yalnızca sayfaya sığmak için sarılır.',code('\n'.join(f'{i+1:02}  {lines[i]}' for i in range(first,last))))
base=(ROOT/'docs/Voku-CMS-Egitim-Rehberi.html').read_text();css=re.search(r'<style>([\s\S]*?)</style>',base).group(1)
css+='\npre{font-size:8pt;line-height:1.4} .cover h1{font-size:37pt} .toc a{padding:1.8mm 0}\n'
cover='<div class="cover"><div><div class="tag">C# VE MVC · DOSYA DOSYA EĞİTİM</div><h1>AdminController<br>Formlar ve modeller</h1><p>Ne işe yarar? Neden böyle tasarlandı?<br>Bir input veritabanına nasıl ulaşır?</p></div><div><p>Ders 02 · Başlangıç seviyesi<br>Gerçek kod, veri akışları ve cevaplı alıştırmalar.</p><div class="meta">Voku CMS · 4c8cf8c kod sürümü<br>AdminController, admin view’ları ve model tasarımı</div></div></div>'
toc=''
for start in range(0,len(parts),14):
 toc+='<section class="toc"><div class="eyebrow">DERS PLANI</div><h1>İçindekiler'+(' · devam' if start else '')+'</h1>'
 toc+=''.join(f'<a href="#lesson-{i+1}">{i+1:02} &nbsp; {parts[i][0]}</a>' for i in range(start,min(start+14,len(parts))))+'</section>'
html='<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>AdminController — Formlar ve Modeller Eğitimi</title><style>'+css+'</style></head><body>'+cover+toc+''.join(x[1] for x in parts)+'</body></html>'
(ROOT/'docs/AdminController-Egitimi.html').write_text(html.replace('<ContentPage>', '&lt;ContentPage&gt;'))
print(f'Admin guide: {len(parts)} chapters')
